export const GET_BLOG_POSTS = 'GET_BLOG_POSTS';
export const SET_BLOG_POSTS = 'SET_BLOG_POSTS';
export const READ_POST_DETAILS = 'READ_POST_DETAILS';
export const SET_POST_TITLE = 'SET_POST_TITLE';
export const SET_POST_CONTENT = 'SET_POST_CONTENT';
export const SET_POST_CATEGORIES = 'SET_POST_CATEGORIES';
export const SAVE_BLOG_POST = 'SAVE_BLOG_POST';
export const RESET_BLOG_FORM = 'RESET_BLOG_FORM';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const SET_FILTERED_BLOG_POSTS = 'SET_FILTERED_BLOG_POSTS';
export const CLEAR_FILTERED_BLOG_POSTS = 'CLEAR_FILTERED_BLOG_POSTS';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const DELETE_BLOG_POST = 'DELETE_BLOG_POST';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';


